# Generated by Django 4.0.2 on 2022-02-11 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('Users', '0006_alter_donation_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_donation', to='projects.projects'),
        ),
    ]
