# Generated by Django 4.0.2 on 2022-02-11 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_donation_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_donation', to='Users.profile'),
        ),
    ]
